version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    command: vendor/bin/phpunit

  phpstan:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    command: vendor/bin/phpstan analyse -c /app/.phpstan.neon
    networks:
      - default

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
